### ISSUE TITLE
Problems I've noticed on 1.0.8.0

### ISSUE THREAD

**Issue by pythonr0ck** [emuPlace/Limon#13]
**Many of these settings are still present in 1.0.8.1 and up**
**Don't feel like making multiple issues so here we are**
### **Virtual Controller**
**- Separate Joysticks**
When joysticks are added, having an option for separate joysticks would be better than having it attached to the buttons on devices like the iPads and some of the larger iPhones. 

**- D-Pad**
The d-pad needs to act like a joystick, or then I'd have to press 2 buttons for diagonal input.

**- Connecting a controller doesn’t seem to work**
### **Settings**
**- Resolution isn’t changing**

**- Customizable controls**

**- Settings screen**
It should stay on after I select an option.

**- Setting buttons aren’t clear**
What does ★ do?

**- Texture filters don’t seem to work**

**- In Game Settings don't save**

**- Custom Textures aren’t in settings**
### **Rom Selection Screen**
**- Cards are too big on iPad**
It'd be nice to scroll left and right on each section to see your roms too.

**- Game Searching not working**

**- Import CIA crashes**
### **Other**
**- Move the ipa to github and the website**

**- Single screen layout**
Invisible touch screen is on the top left part of the screen, but isn't supposed to be there at all.
### **Suggestions**
**- Rom Selection UI Suggestion**
I think having a rom selection ui similar to UTM and using the old 1.0.6.4 design to match would look nice. [Something like this](https://github.com/emuPlace/Limon/assets/122493008/94f3e719-c1af-434d-bd70-732728db20aa) 
(Placing more options like pinning roms could be added by splitting the play button or by placing the other buttons next to the title, cutting off the title and rotating through it or cut off with … when needed.)
(Search and edit buttons could also be added next to the settings icon to search roms and add folders)
(The icon could also be replaced with the rom icon or with the last image of gameplay instead if it isn’t possible)

**- Folders**
To sort your roms

**Comment by dylan8863** [comment]
How did you install limon

**Comment by PitayoSan** [comment]
@pythonr0ck
How do you manage to make "Import CIA" work?
It always crashes on my device.

**Comment by pythonr0ck** [comment]
> @pythonr0ck
> How do you manage to make "Import CIA" work?
> It always crashes on my device.

Seems like it only worked when I first launched Limon after sideloading. Sorry for the late reply!

**Comment by pythonr0ck** [comment]
> How did you install limon @pythonr0ck 

Scarlet + dnscloak revoke block
