### ISSUE TITLE
Crashing Limon v1.0.8.0 iOS 14.4.2

### ISSUE THREAD

**Issue by Progamer78** [emuPlace/Limon#16]
Trying this out on iOS 14.4.2 iPhone Xr
It does say iOS 16 minimum inside the plist but when I changed it and installed the app it then goes i to install crash.
Is there any reason why it’s not workable on this version and is there a way to get around that?
Btw I meant Limon v1.0.8.3

**Comment by jarrodnorwell** [comment]
Hey @Progamer78, the reason for it only supporting iOS 15 and above right now is due to the Citra core and some of the UI, I'm not sure if it will ever support 14 as most of the devices with that version simply cannot run 3DS games well enough
