### ISSUE TITLE
Where do I download ??

### ISSUE THREAD

**Issue by justaniceguy100** [emuPlace/Limon#17]
How do I install it to my iPhone ???

**Comment by C4ndyF1sh** [comment]
Grab the latest .ipa from here https://www.buymeacoffee.com/jarrodnorwell/muretazuxe
Then sideload through AltServer/AltStore, SideServer/SideStore, Sideloadly etc. if you have a PC, if not then install it through Scarlet

**Comment by justaniceguy100** [comment]
Thanks
