### ISSUE TITLE
(v1.0.8.3 build 3) CIA imports do not work

### ISSUE THREAD

**Issue by Setnour6** [emuPlace/Limon#28]
Using iOS 17.1.1 with AltStore, non-jailbroken

Sideloaded apps: AltStore, EmuThreeDS, Limon
Inactive apps: Delta, RetroArch

### Description

When loading a CIA, in the case of Mario and Luigi Dream Team, I get a message that says "installing" and directing me to a loading screen, but then back to the games section with no game displaying.

### Reproduction

1. Open the app
2. Import the CIA (assuming you know how to do that)
3. Wait for the installing message to finish
4. Get the loading screen with a blurred background
5. You are sent back to the games section with no CIA loaded

This happens 100% of the time.

I also tried the first build of the same version but nothing worked.

**Comment by Panky55** [comment]
Prob because you got the via from a website instead of dumping it yourself

**Comment by Panky55** [comment]
If you don’t have the game to dump then I recommend at least dumping your aes keys so Limon can decrypt them it self or at least I think that’s how it should work

**Comment by Setnour6** [comment]
> If you don’t have the game to dump then I recommend at least dumping your aes keys so Limon can decrypt them it self or at least I think that’s how it should work

I have the keys but the only known mention of a directory is `sysdata/aes_keys.txt`. I wanted to try it on Citra first but loading the non-decrypted game via the listed game directory doesn't work.
I just added it to my phone in the same directory and the game appeared (which is great), but only the non-decrypted one (which is fine).
This pretty much solves the issue I have with CIA imports not working, with me now realizing that the aes_keys.txt file is needed. Thank you for your help @Panky55
