### ISSUE TITLE
Pokemon Omega Ruby Crashed while starting the game

### ISSUE THREAD

**Issue by Zafurz** [emuPlace/Limon#50]
Iphone 12 Pro
IOS 17
Limon v1.0.8.5 (1)

I haven't tried any other games yet but why not try this game, btw I have a screen record of how it crashes in comment section

**Comment by Zafurz** [comment]
https://youtube.com/shorts/mkABYWRvy_U?si=8h_fyiOqvw2Mi1j3

**Comment by Zafurz** [comment]
NVM JUST FIXED IT I TURNED OFF "HARDWARE SHADER" THATS IT!!

**Comment by Panky55** [comment]
Do you have trollstore?
